#pragma once

#define APP_CONTROLLER_TASK_STACK_SIZE 4096
#define APP_CONTROLLER_TASK_PRIORITY 5

#define ZIGBEE_CONTROLLER_TASK_STACK_SIZE 8192
#define ZIGBEE_CONTROLLER_TASK_PRIORITY 5

#define NAVIGATION_CYCLE_TASK_STACK_SIZE 6144
#define NAVIGATION_CYCLE_TASK_PRIORITY 5

#define NAVIGATION_EVENT_TASK_STACK_SIZE 4096
#define NAVIGATION_EVENT_TASK_PRIORITY 6

