#pragma once

#include <stdint.h>

#define NAVIGATION_LISTEN_WINDOW_MS 1500U
#define NAVIGATION_MIN_LISTEN_WINDOW_MS 1000U
#define NAVIGATION_SLEEP_INTERVAL_MS 5000U
#define NAVIGATION_RETRY_INTERVAL_MS 1000U
#define NAVIGATION_MAX_SAMPLES 12U
#define NAVIGATION_MIN_SAMPLES_FOR_POSITION 2U
#define NAVIGATION_MAX_ACCEPTED_SEQUENCE_DELAY_CYCLES 5U

#define NAVIGATION_RSSI_AT_ONE_METER_DBM (-59.0f)
#define NAVIGATION_PATH_LOSS_EXPONENT 2.2f

static constexpr uint16_t kDefaultNodeId = 0x0001;
