#pragma once

#include <stdint.h>

#define ZIGBEE_PRIMARY_CHANNEL_MASK 0x07FFF800U
#define ZIGBEE_SECONDARY_CHANNEL_MASK 0x07FFF800U
#define ZIGBEE_ENDPOINT_NAVIGATION 10U
#define ZIGBEE_KEEP_ALIVE_MS 3000U
#define ZIGBEE_BDB_SCAN_DURATION 5U
#define ZIGBEE_COMMISSIONING_RETRY_DELAY_MS 10000U
#define ZIGBEE_SEND_LOCK_TIMEOUT_MS 50U
#define ZIGBEE_RX_ON_WHEN_IDLE true

#define CUSTOM_NAV_CLUSTER_ID 0xFF01U
#define CMD_PING_REQ 0x01U
#define CMD_PING_RSP 0x02U

#define ZIGBEE_BROADCAST_RX_ON_WHEN_IDLE 0xFFFDU
