#pragma once

#include <stdint.h>

#define ZIGBEE_PRIMARY_CHANNEL_MASK 0x07FFF800U
#define ZIGBEE_ENDPOINT_NAVIGATION 10U
#define ZIGBEE_KEEP_ALIVE_MS 3000U

#define CUSTOM_NAV_CLUSTER_ID 0xFF01U
#define CMD_PING_REQ 0x01U
#define CMD_PING_RSP 0x02U

#define ZIGBEE_BROADCAST_RX_ON_WHEN_IDLE 0xFFFDU

