#pragma once

#define APP_CONTROLLER_TASK_STACK_SIZE 4096
#define APP_CONTROLLER_TASK_PRIORITY 5

#define ZIGBEE_CONTROLLER_TASK_STACK_SIZE 8192
#define ZIGBEE_CONTROLLER_TASK_PRIORITY 5

#define ROUTER_EVENT_TASK_STACK_SIZE 4096
#define ROUTER_EVENT_TASK_PRIORITY 6

#define ROUTER_DIAGNOSTIC_TASK_STACK_SIZE 3072
#define ROUTER_DIAGNOSTIC_TASK_PRIORITY 3
#define ROUTER_DIAGNOSTIC_INTERVAL_MS 10000U
