#pragma once

#include <stdint.h>

#define ZIGBEE_PRIMARY_CHANNEL_MASK 0x07FFF800U
#define ZIGBEE_SECONDARY_CHANNEL_MASK 0x07FFF800U
#define ZIGBEE_ENDPOINT_NAVIGATION 10U
#define ZIGBEE_KEEP_ALIVE_MS 3000U
#define ZIGBEE_ROUTER_MAX_CHILDREN 10U
#define ZIGBEE_BDB_SCAN_DURATION 5U
#define ZIGBEE_STEERING_RETRY_DELAY_MS 10000U
